# Generated by Django 4.0.4 on 2022-06-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
